### ISSUE TITLE
error while executing

### ISSUE THREAD

**Issue by avinash8494** [MuhammedBuyukkinaci/TensorFlow-Sentiment-Analysis-on-Amazon-Reviews-Data#1]
The issue is Coming while involving  100-Dimensional GloVe Word Embeddings for this project.

Here i am using Notepad++
Traceback (most recent call last):
  File "08_CPU_Optimized_LSTM.py", line 93, in <module>
    print(open(os.path.join(working_dir,EMBEDDING_FILE),'r' ).read())
  File "C:\Users\AppData\Local\Programs\Python\Python35\lib\encodings\cp
1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 1215192:
character maps to <undefined>

**Comment by MuhammedBuyukkinaci** [comment]
Hi,
Sorry for late response. I didn't see. You can take a look at [this question on stackoverflow](https://stackoverflow.com/questions/9233027/unicodedecodeerror-charmap-codec-cant-decode-byte-x-in-position-y-character).

The problem is about encodings. Maybe, it is related to your OS because you are using Windows and I made this project on Linux.
